name: skip jobs
run-name: skip jobs (max-job=${{ inputs.max-job }}, fail-base-dependency=${{ inputs.fail-base-dependency }}) by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      max-job:
        type: number
        required: false
        default: 3
      fail-base-dependency:
        type: boolean
        required: false
        default: true

jobs:
  base_dependency:
    runs-on: ubuntu-latest
    if: success() && inputs.max-job >= 1
    steps:
      - run: |
          echo "base_dependency job"
          if [ "${{ inputs.fail-base-dependency }}" = "true" ]; then
            exit 1
          fi

  skip:
    runs-on: ubuntu-latest
    needs: base_dependency
    if: success() && inputs.max-job >= 2
    steps:
      - run: echo "this job should have been skipped"
      

  deploy:
    needs: skip
    runs-on: ubuntu-latest
    if: success() && inputs.max-job >= 3
    steps:
      - run: echo "Deploy"
