name: skip jobs

on:
  workflow_dispatch:
    inputs:
      max-job:
        type: number
        required: false
        default: 3
  
jobs:
  fail:
    runs-on: ubuntu-latest
    if: success() && inputs.max-job >= 1
    steps:
      - run: |
          echo "fail job"
          exit 1

  skip:
    runs-on: ubuntu-latest
    needs: fail
    if: success() && inputs.max-job >= 2
    steps:
      - run: echo "this job should have been skipped"
      

  deploy:
    needs: skip
    runs-on: ubuntu-latest
    if: success() && inputs.max-job >= 3
    steps:
      - run: echo "Deploy"
